// Copyright (c) 2026 the go-opentype/shape authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

package main

import (
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// stubServer serves the two UCD files from an in-memory map, 404 otherwise.
func stubServer(files map[string]string) *httptest.Server {
	mux := http.NewServeMux()
	for path, body := range files {
		body := body
		mux.HandleFunc(path, func(w http.ResponseWriter, r *http.Request) {
			io.WriteString(w, body)
		})
	}
	return httptest.NewServer(mux)
}

const iscStub = `# comment
0900..0902    ; Bindu # Mn
0915          ; Consonant # Lo
0930          ; Consonant # Lo
093F          ; Vowel_Dependent # Mc
094D          ; Virama # Mn
`

const ipcStub = `# comment

0900..0902    ; Top
093F          ; Left
094D          ; Bottom
`

func TestParseRange(t *testing.T) {
	lo, hi, err := parseRange("0900..0902")
	if err != nil || lo != 0x0900 || hi != 0x0902 {
		t.Errorf("parseRange range = %#x,%#x,%v", lo, hi, err)
	}
	lo, hi, err = parseRange("0915")
	if err != nil || lo != 0x0915 || hi != 0x0915 {
		t.Errorf("parseRange single = %#x,%#x,%v", lo, hi, err)
	}
	if _, _, err := parseRange("ZZ..0902"); err == nil {
		t.Error("parseRange bad lo: want error")
	}
	if _, _, err := parseRange("0900..ZZ"); err == nil {
		t.Error("parseRange bad hi: want error")
	}
	if _, _, err := parseRange("ZZ"); err == nil {
		t.Error("parseRange bad single: want error")
	}
}

func TestParseUCD(t *testing.T) {
	m, err := parseUCD([]byte(iscStub))
	if err != nil {
		t.Fatalf("parseUCD: %v", err)
	}
	if m[0x0915] != "Consonant" || m[0x0901] != "Bindu" {
		t.Errorf("parseUCD map = %v", m)
	}
	if _, err := parseUCD([]byte("0900 ; A ; B\n")); err == nil {
		t.Error("bad field count: want error")
	}
	if _, err := parseUCD([]byte("ZZ ; Bindu\n")); err == nil {
		t.Error("bad range: want error")
	}
}

func TestGenerate(t *testing.T) {
	isc, _ := parseUCD([]byte(iscStub))
	ipc, _ := parseUCD([]byte(ipcStub))
	src, err := generate(isc, ipc)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	s := string(src)
	for _, want := range []string{
		"Code generated by cmd/genindic; DO NOT EDIT.",
		"package shape",
		"var indicData = []indicRange{",
		"{0x0900, 0x0902, catSM, posAboveC}",
		"{0x0915, 0x0915, catC, posEnd}",
		"{0x093F, 0x093F, catM, posPreM}",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("generated source missing %q\n%s", want, s)
		}
	}

	// Unmapped syllabic category.
	if _, err := generate(map[rune]string{0x0900: "Nonsense"}, nil); err == nil {
		t.Error("unmapped ISC: want error")
	}
	// Unmapped positional category.
	if _, err := generate(map[rune]string{0x0900: "Bindu"}, map[rune]string{0x0900: "Sideways"}); err == nil {
		t.Error("unmapped IPC: want error")
	}
}

func TestFetchProp(t *testing.T) {
	srv := stubServer(map[string]string{"/isc": iscStub})
	defer srv.Close()
	m, err := fetchProp(srv.URL + "/isc")
	if err != nil || m[0x0915] != "Consonant" {
		t.Fatalf("fetchProp = %v, %v", m, err)
	}
	// 404.
	if _, err := fetchProp(srv.URL + "/missing"); err == nil {
		t.Error("404: want error")
	}
	// Transport error (bad scheme host).
	if _, err := fetchProp("http://127.0.0.1:0/x"); err == nil {
		t.Error("transport error: want error")
	}
}

// errBody is a ReadCloser whose Read always fails, to hit the io.ReadAll error.
type errBody struct{}

func (errBody) Read([]byte) (int, error) { return 0, errors.New("boom") }
func (errBody) Close() error             { return nil }

func TestFetchPropReadError(t *testing.T) {
	orig := httpGet
	httpGet = func(string) (*http.Response, error) {
		return &http.Response{StatusCode: 200, Body: errBody{}}, nil
	}
	defer func() { httpGet = orig }()
	if _, err := fetchProp("http://x/y"); err == nil {
		t.Error("read error: want error")
	}
}

func TestRun(t *testing.T) {
	srv := stubServer(map[string]string{"/isc": iscStub, "/ipc": ipcStub})
	defer srv.Close()
	out := filepath.Join(t.TempDir(), "indictables.go")

	// Usage error.
	if code := run(nil); code != 2 {
		t.Errorf("run(nil) = %d, want 2", code)
	}
	// Syllabic fetch fails.
	if code := run([]string{srv.URL + "/missing", srv.URL + "/ipc", out}); code != 1 {
		t.Errorf("run bad isc = %d, want 1", code)
	}
	// Positional fetch fails.
	if code := run([]string{srv.URL + "/isc", srv.URL + "/missing", out}); code != 1 {
		t.Errorf("run bad ipc = %d, want 1", code)
	}
	// Success.
	if code := run([]string{srv.URL + "/isc", srv.URL + "/ipc", out}); code != 0 {
		t.Fatalf("run ok = %d, want 0", code)
	}
	if b, err := os.ReadFile(out); err != nil || !strings.Contains(string(b), "var indicData") {
		t.Errorf("output not written: %v", err)
	}
}

func TestRunGenerateError(t *testing.T) {
	// A syllabic file with an unmapped category makes generate fail.
	srv := stubServer(map[string]string{
		"/isc": "0900 ; Nonsense\n",
		"/ipc": ipcStub,
	})
	defer srv.Close()
	out := filepath.Join(t.TempDir(), "x.go")
	if code := run([]string{srv.URL + "/isc", srv.URL + "/ipc", out}); code != 1 {
		t.Errorf("run generate error = %d, want 1", code)
	}
}

func TestRunWriteError(t *testing.T) {
	srv := stubServer(map[string]string{"/isc": iscStub, "/ipc": ipcStub})
	defer srv.Close()
	orig := writeF
	writeF = func(string, []byte, os.FileMode) error { return errors.New("nope") }
	defer func() { writeF = orig }()
	if code := run([]string{srv.URL + "/isc", srv.URL + "/ipc", "/whatever"}); code != 1 {
		t.Errorf("run write error = %d, want 1", code)
	}
}

func TestMain2(t *testing.T) {
	srv := stubServer(map[string]string{"/isc": iscStub, "/ipc": ipcStub})
	defer srv.Close()
	out := filepath.Join(t.TempDir(), "m.go")

	origExit, origArgs := osExit, os.Args
	var code int
	osExit = func(c int) { code = c }
	os.Args = []string{"genindic", srv.URL + "/isc", srv.URL + "/ipc", out}
	defer func() { osExit, os.Args = origExit, origArgs }()

	main()
	if code != 0 {
		t.Errorf("main exit = %d, want 0", code)
	}
	if _, err := os.Stat(out); err != nil {
		t.Errorf("main did not write output: %v", err)
	}
}
