// Copyright (c) 2026 the go-opentype/shape authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

package main

import (
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// stubServer serves the UCD files from an in-memory map, 404 otherwise.
func stubServer(files map[string]string) *httptest.Server {
	mux := http.NewServeMux()
	for path, body := range files {
		body := body
		mux.HandleFunc(path, func(w http.ResponseWriter, r *http.Request) {
			io.WriteString(w, body)
		})
	}
	return httptest.NewServer(mux)
}

const iscStub = `# comment

0E01..0E02    ; Consonant # Lo
0E35          ; Vowel_Dependent # Mn
0E48          ; Tone_Mark # Mn
1F00          ; Nonsense # Xx
`

const ipcStub = `# comment
0E34..0E37    ; Top
0E48..0E4B    ; Top
0E4F          ; Right
`

const gcStub = `0E01..0E02    ; Lo
0E35          ; Mn
0E48          ; Mn
`

const scriptsStub = `# comment
0E01..0E3A    ; Thai
0E40..0E4E    ; Thai
0E81..0E82    ; Lao
0041..005A    ; Latin
`

func TestParseRange(t *testing.T) {
	lo, hi, err := parseRange("0E01..0E02")
	if err != nil || lo != 0x0E01 || hi != 0x0E02 {
		t.Errorf("parseRange range = %#x,%#x,%v", lo, hi, err)
	}
	lo, hi, err = parseRange("0E35")
	if err != nil || lo != 0x0E35 || hi != 0x0E35 {
		t.Errorf("parseRange single = %#x,%#x,%v", lo, hi, err)
	}
	if _, _, err := parseRange("ZZ..0E02"); err == nil {
		t.Error("parseRange bad lo: want error")
	}
	if _, _, err := parseRange("0E01..ZZ"); err == nil {
		t.Error("parseRange bad hi: want error")
	}
	if _, _, err := parseRange("ZZ"); err == nil {
		t.Error("parseRange bad single: want error")
	}
}

func TestParseUCD(t *testing.T) {
	m, err := parseUCD([]byte(iscStub))
	if err != nil {
		t.Fatalf("parseUCD: %v", err)
	}
	if m[0x0E01] != "Consonant" || m[0x0E48] != "Tone_Mark" {
		t.Errorf("parseUCD map = %v", m)
	}
	if _, err := parseUCD([]byte("0E01 ; A ; B\n")); err == nil {
		t.Error("bad field count: want error")
	}
	if _, err := parseUCD([]byte("ZZ ; Consonant\n")); err == nil {
		t.Error("bad range: want error")
	}
}

func TestGenerate(t *testing.T) {
	isc, _ := parseUCD([]byte(iscStub))
	ipc, _ := parseUCD([]byte(ipcStub))
	gc, _ := parseUCD([]byte(gcStub))
	sc, _ := parseUCD([]byte(scriptsStub))
	s := string(generate(isc, ipc, gc, sc))
	for _, want := range []string{
		"Code generated by cmd/genuse from the Unicode Character Database; DO NOT EDIT.",
		"package shape",
		"var useRanges = []useRange{",
		"{0x0E01, 0x0E02, ucB},",     // coalesced consonants
		"{0x0E35, 0x0E35, ucVAbv},",  // above vowel
		"{0x0E48, 0x0E48, ucVMAbv},", // tone mark, above
		"{0x0E4F, 0x0E4F, ucIND},",   // ipc-only rune -> uisc defaults Other -> IND
		"{0x034F, 0x034F, ucCGJ},",   // override
		"{0xFE00, 0xFE0F, ucVS},",    // override, coalesced
		"var useScriptRanges = []u32range{",
		"{0x0E01, 0x0E3A},", // Thai range 1
		"{0x0E40, 0x0E4E},", // Thai range 2 (non-adjacent -> separate)
		"{0x0E81, 0x0E82},", // Lao
	} {
		if !strings.Contains(s, want) {
			t.Errorf("generated source missing %q\n%s", want, s)
		}
	}
	// The bogus-category rune classifies as Other and is not emitted.
	if strings.Contains(s, "0x1F00") {
		t.Errorf("Other-category rune should be skipped:\n%s", s)
	}
	// The excluded Latin script must not appear in the script ranges.
	if strings.Contains(s, "0x0041, 0x005A") {
		t.Errorf("non-USE script should be excluded:\n%s", s)
	}
}

func TestFetchProp(t *testing.T) {
	srv := stubServer(map[string]string{"/isc": iscStub})
	defer srv.Close()
	m, err := fetchProp(srv.URL + "/isc")
	if err != nil || m[0x0E01] != "Consonant" {
		t.Fatalf("fetchProp = %v, %v", m, err)
	}
	if _, err := fetchProp(srv.URL + "/missing"); err == nil {
		t.Error("404: want error")
	}
	if _, err := fetchProp("http://127.0.0.1:0/x"); err == nil {
		t.Error("transport error: want error")
	}
	// A malformed body surfaces the parse error through fetchProp.
	bad := stubServer(map[string]string{"/bad": "ZZ ; X\n"})
	defer bad.Close()
	if _, err := fetchProp(bad.URL + "/bad"); err == nil {
		t.Error("parse error: want error")
	}
}

// errBody is a ReadCloser whose Read always fails, to hit the io.ReadAll error.
type errBody struct{}

func (errBody) Read([]byte) (int, error) { return 0, errors.New("boom") }
func (errBody) Close() error             { return nil }

func TestFetchPropReadError(t *testing.T) {
	orig := httpGet
	httpGet = func(string) (*http.Response, error) {
		return &http.Response{StatusCode: 200, Body: errBody{}}, nil
	}
	defer func() { httpGet = orig }()
	if _, err := fetchProp("http://x/y"); err == nil {
		t.Error("read error: want error")
	}
}

func TestRun(t *testing.T) {
	srv := stubServer(map[string]string{
		"/isc": iscStub, "/ipc": ipcStub, "/gc": gcStub, "/sc": scriptsStub,
	})
	defer srv.Close()
	out := filepath.Join(t.TempDir(), "use_table.go")
	ok := []string{srv.URL + "/isc", srv.URL + "/ipc", srv.URL + "/gc", srv.URL + "/sc", out}

	if code := run(nil); code != 2 {
		t.Errorf("run(nil) = %d, want 2", code)
	}
	// Each fetch failure returns 1.
	for i := 0; i < 4; i++ {
		args := append([]string(nil), ok...)
		args[i] = srv.URL + "/missing"
		if code := run(args); code != 1 {
			t.Errorf("run bad arg %d = %d, want 1", i, code)
		}
	}
	if code := run(ok); code != 0 {
		t.Fatalf("run ok = %d, want 0", code)
	}
	if b, err := os.ReadFile(out); err != nil || !strings.Contains(string(b), "var useRanges") {
		t.Errorf("output not written: %v", err)
	}
}

func TestRunWriteError(t *testing.T) {
	srv := stubServer(map[string]string{
		"/isc": iscStub, "/ipc": ipcStub, "/gc": gcStub, "/sc": scriptsStub,
	})
	defer srv.Close()
	orig := writeF
	writeF = func(string, []byte, os.FileMode) error { return errors.New("nope") }
	defer func() { writeF = orig }()
	args := []string{srv.URL + "/isc", srv.URL + "/ipc", srv.URL + "/gc", srv.URL + "/sc", "/whatever"}
	if code := run(args); code != 1 {
		t.Errorf("run write error = %d, want 1", code)
	}
}

func TestMain2(t *testing.T) {
	srv := stubServer(map[string]string{
		"/isc": iscStub, "/ipc": ipcStub, "/gc": gcStub, "/sc": scriptsStub,
	})
	defer srv.Close()
	out := filepath.Join(t.TempDir(), "m.go")

	origExit, origArgs := osExit, os.Args
	var code int
	osExit = func(c int) { code = c }
	os.Args = []string{"genuse", srv.URL + "/isc", srv.URL + "/ipc", srv.URL + "/gc", srv.URL + "/sc", out}
	defer func() { osExit, os.Args = origExit, origArgs }()

	main()
	if code != 0 {
		t.Errorf("main exit = %d, want 0", code)
	}
	if _, err := os.Stat(out); err != nil {
		t.Errorf("main did not write output: %v", err)
	}
}
